# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sockets.io' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sockets.io
  pod 'Starscream', '~> 3.0'
  pod 'Socket.IO-Client-Swift', '~> 13.1.0'

end
